baseURL = 'https://RussellXX.github.io/'
languageCode = 'zh-CN'
title = "RR's notes"
theme = 'PaperMod'

[params]
  homeInfoParams = {Title = "学习笔记", Content = "记录每天的学习成果"}
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true      # 代码块一键复制
  math = true                      # 开启 LaTeX

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github"

[[menus.main]]
  name = "文章"
  url = "/posts/"
  weight = 1

[[menus.main]]
  name = "分类"
  url = "/categories/"
  weight = 2

[taxonomies]
  category = "categories"
