baseURL = 'https://RussellXX.github.io/'
languageCode = 'zh-CN'
title = "RR's notes"
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  math = true

  [params.homeInfoParams]
    Title = "学习笔记"
    Content = "记录每天的学习成果"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github"

[[menus.main]]
  name = "文章"
  url = "/posts/"
  weight = 1

[[menus.main]]
  name = "分类"
  url = "/categories/"
  weight = 2

[taxonomies]
  category = "categories"
